sudo: required
dist: precise

language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'

before_install:
 - sudo ./clamav-travis.sh

addons:
   hosts:
     - avscan